In [2]:
import csv
import pandas as pd
import os
import sys

In [3]:
path = '.'

files=[]
# r=root, d=directories, f = files
for r, d, f in os.walk(path):
    for file in f:
        if '.csv' in file:
            files.append(os.path.join(r, file))

In [4]:
files

['./datos_2018.csv',
 './datos_2019.csv',
 './datos_2017.csv',
 './datos_2016.csv',
 './datos_2015.csv']

In [5]:
headers=[
    "fecha", "indicativo", "nombre", "provincia", "altitud", 
    "tmed", "prec", "tmin", "htmin", "tmax", "htmax", "dir", 
    "velmedia", "racha", "horaracha", "sol", "presmax", "horapresmax",
    "presmin", "horapresmin"
]

In [16]:
datos2015csv = pd.read_csv("datos_2015.csv", sep=";")
datos2016csv = pd.read_csv("datos_2016.csv", sep=";")
datos2017csv = pd.read_csv("datos_2017.csv", sep=";")
datos2018csv = pd.read_csv("datos_2018.csv", sep=";")
datos2019csv = pd.read_csv("datos_2019.csv", sep=";")

In [7]:
datos2015csv.head()

,2015-01-01,4358X,DON BENITO,BADAJOZ,273,"5,6","0,0","-2,6",07:40,"13,7",15:30,36,"0,8","3,6",13:40,"8,4","1004,2",Varias,"999,9",02
0,2015-01-01,4220X,PUEBLA DE DON RODRIGO,CIUDAD REAL,486,"2,9","-7,0",06:10,"12,8",14:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01,C447A,TENERIFE NORTE AEROPUERTO,STA. CRUZ DE TENERIFE,632,"13,0","0,0","11,6",20:36,"14,5",12:14,99,"6,7","12,8",Varias,"3,4","957,7",Varias,"954,3",01
2,2015-01-01,6106X,ANTEQUERA,MALAGA,408,"4,6","0,0","-4,9",08:00,"14,1",13:10,16,"3,1","12,5",12:00,"986,9",24,"981,5",02,NaN
3,2015-01-01,9698U,TALARN,LLEIDA,807,"4,8","0,0","-0,2",03:20,"9,9",14:50,"7,6","940,0",23,"933,8",00,NaN,NaN,NaN,NaN
4,2015-01-01,4410X,MRIDA,BADAJOZ,228,"6,0","0,0","-2,3",06:50,"14,3",15:50,09,"1,1","5,0",11:30,NaN,NaN,NaN,NaN,NaN

In [8]:
combined_csv = pd.concat([datos2015csv, datos2016csv, datos2017csv, datos2018csv, datos2019csv], axis=1)
#export to csv

In [9]:
combined_csv.head()

,2015-01-01,4358X,DON BENITO,BADAJOZ,273,"5,6","0,0","-2,6",07:40,"13,7",...,15:50,15,"0,8","3,3",21:00,"8,4","1000,3",10,"997,8",01
0,2015-01-01,4220X,PUEBLA DE DON RODRIGO,CIUDAD REAL,486,"2,9","-7,0",06:10,"12,8",14:50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-01-01,C447A,TENERIFE NORTE AEROPUERTO,STA. CRUZ DE TENERIFE,632,"13,0","0,0","11,6",20:36,"14,5",...,15:30,16,"3,9","11,4",10:11,"5,5","956,5",Varias,"951,2",01
2,2015-01-01,6106X,ANTEQUERA,MALAGA,408,"4,6","0,0","-4,9",08:00,"14,1",...,15:10,15,"0,8","7,2",00:20,"982,8",10,"980,5",05,NaN
3,2015-01-01,9698U,TALARN,LLEIDA,807,"4,8","0,0","-0,2",03:20,"9,9",...,14:40,19,"0,8","2,8",00:50,"7,7","935,8",09,"933,5",24
4,2015-01-01,4410X,MRIDA,BADAJOZ,228,"6,0","0,0","-2,3",06:50,"14,3",...,15:40,09,"0,6","4,2",10:00,NaN,NaN,NaN,NaN,NaN

In [10]:
combined_csv.columns = headers

ValueError: Length mismatch: Expected axis has 100 elements, new values have 20 elements

In [11]:
combined_csv.fillna(value="Error")

,2015-01-01,4358X,DON BENITO,BADAJOZ,273,"5,6","0,0","-2,6",07:40,"13,7",...,15:50,15,"0,8","3,3",21:00,"8,4","1000,3",10,"997,8",01
0,2015-01-01,4220X,PUEBLA DE DON RODRIGO,CIUDAD REAL,486,"2,9","-7,0",06:10,"12,8",14:50,...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
1,2015-01-01,C447A,TENERIFE NORTE AEROPUERTO,STA. CRUZ DE TENERIFE,632,"13,0","0,0","11,6",20:36,"14,5",...,15:30,16,"3,9","11,4",10:11,"5,5","956,5",Varias,"951,2",01
2,2015-01-01,6106X,ANTEQUERA,MALAGA,408,"4,6","0,0","-4,9",08:00,"14,1",...,15:10,15,"0,8","7,2",00:20,"982,8",10,"980,5",05,Error
3,2015-01-01,9698U,TALARN,LLEIDA,807,"4,8","0,0","-0,2",03:20,"9,9",...,14:40,19,"0,8","2,8",00:50,"7,7","935,8",09,"933,5",24
4,2015-01-01,4410X,MRIDA,BADAJOZ,228,"6,0","0,0","-2,3",06:50,"14,3",...,15:40,09,"0,6","4,2",10:00,Error,Error,Error,Error,Error
5,2015-01-01,1331A,CASTROPOL,ASTURIAS,40,"9,7","0,0","2,6",Varias,"16,8",...,14:10,10,"1,1","5,8",21:30,Error,Error,Error,Error,Error
6,2015-01-01,1690A,OURENSE,OURENSE,143,"4,6","0,0","-3,8",07:30,"13,0",...,16:10,99,"0,8","2,2",Varias,"4,2","1017,3",10,"1014,1",Varias
7,2015-01-01,0002I,VANDELLS,TARRAGONA,32,30,"0,3","8,3",20:40,Error,...,12:40,22,"1,4","8,6",03:20,Error,Error,Error,Error,Error
8,2015-01-01,8489X,VILLAFRANCA DEL CID/VILLAFRANCA,CASTELLON,1131,"2,0","0,0","-5,8",08:00,"9,9",...,14:20,31,"3,1","6,4",23:30,"8,4","901,0",10,"898,9",Varias
9,2015-01-01,8025,ALICANTE/ALACANT,ALICANTE,81,"9,6","0,0","3,2",07:30,"16,0",...,14:10,99,"1,9","6,9",Varias,"8,9","1020,8",10,"1018,3",14
10,2015-01-01,C449C,STA.CRUZ DE TENERIFE,STA. CRUZ DE TENERIFE,35,"19,0","0,0","17,4",23:30,"20,6",...,15:20,20,"3,1","8,6",13:00,"9,3","1023,3",Varias,"1018,1",01
11,2015-01-01,9784P,BIELSA,HUESCA,992,"3,4","0,0","-1,8",08:00,"8,5",...,11:50,32,"1,1","10,3",23:10,"3,9","915,4",09,"913,0",24
12,2015-01-01,2331,BURGOS AEROPUERTO,BURGOS,891,"3,0","0,0","-5,5",07:30,"11,5",...,14:10,06,"2,8","7,8",10:50,"8,8","928,9",10,"927,2",14
13,2015-01-01,9434,ZARAGOZA AEROPUERTO,ZARAGOZA,249,"6,2","0,0","-0,2",08:10,"12,6",...,14:50,30,"1,9","8,3",23:59,"4,2","1002,0",10,"999,2",16
14,2015-01-01,1109,SANTANDER AEROPUERTO,CANTABRIA,3,"7,2","0,0","-0,4",07:30,"14,9",...,12:15,13,"1,9","5,3",10:30,"0,5","1036,6",Varias,"1033,3",04
15,2015-01-01,6293X,ROQUETAS DE MAR,ALMERIA,3,"10,3","0,0","3,5",04:10,"17,1",...,14:50,99,"2,8","5,3",Varias,"0,0","1031,7",Varias,"1029,3",Varias
16,2015-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,"9,0","0,0","3,2",07:30,"14,7",...,13:30,13,"4,7","8,9",10:44,"2,1","1020,2",Varias,"1016,8",01
17,2015-01-01,3094B,TARANCN,CUENCA,808,"6,0","0,0","-0,3",05:00,"12,4",...,16:00,03,"0,8","2,8",12:30,"7,3","963,7",09,"960,2",16
18,2015-01-01,1059X,PUNTA GALEA,BIZKAIA,90,"7,4","0,0","1,1",06:20,"13,8",...,15:00,25,"1,4","3,3",14:10,"936,0",10,"934,2",05,Error
19,2015-01-01,1207U,"GIJN, CAMPUS",ASTURIAS,26,"6,4","0,0","-1,8",07:20,"14,6",...,14:00,16,"1,7","4,2",Varias,"1026,2",Varias,"1023,0",04,Error
20,2015-01-01,6367B,HURCAL-OVERA,ALMERIA,300,"9,8","0,0","2,3",04:10,"17,2",...,13:50,08,"2,5","8,1",14:10,"5,1","1032,5",Varias,"1029,2",02
21,2015-01-01,7228,"ALCANTARILLA, BASE AREA",MURCIA,75,"8,6","0,0","1,5",Varias,"15,8",...,11:50,21,"0,8","6,9",13:40,"996,5",09,"993,0",24,Error
22,2015-01-01,3168C,"GUADALAJARA, EL SERRANILLO",GUADALAJARA,639,"2,8","0,0","-8,1",06:54,"13,6",...,14:50,26,"1,9","6,1",17:07,"8,9","1023,3",10,"1020,0",16
23,2015-01-01,7002Y,GUILAS,MURCIA,26,"12,2","0,0","7,7",21:50,"16,6",...,14:20,19,"1,7","4,2",13:30,"8,1","1028,1",10,"1025,1",24
24,2015-01-01,C649I,GRAN CANARIA AEROPUERTO,LAS PALMAS,32,"18,6","0,0","16,9",19:24,"20,2",...,12:50,99,"2,5","8,3",Varias,"9,3","1022,6",Varias,"1017,5",01
25,2015-01-01,3191E,COLMENAR VIEJO,MADRID,1004,"7,0","0,0","3,4",07:50,"10,5",...,Varias,15,"0,3","3,6",12:50,"8,4","915,0",10,"914,0",Varias
26,2015-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,"6,2","0,0","-1,1",00:42,"13,5",...,13:05,26,"1,7","7,8",14:27,"9,0","1021,4",Varias,"1018,6",24
27,2015-01-01,8058X,OLIVA,VALENCIA,5,"10,0","0,0","4,4",01:20,"15,5",...,12:10,26,"0,8","2,5",01:00,Error,Error,Error,Error,Error
28,2015-01-01,0367,GIRONA AEROPUERTO,GIRONA,143,"5,2","0,0","-2,1",07:15,"12,6",...,13:09,99,"1,4","5,8",Varias,"7,8","1014,6",Varias,"1010,5",24
29,2015-01-01,7247X,PINOSO,ALICANTE,575,"3,7","0,0","-4,7",06:50,"12,1",...,15:10,24,"1,4","4,7",11:30,Error,Error,Error,Error,Error
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93919,2015-12-31,9001D,REINOSA,CANTABRIA,870,"2,8","0,0","-3,1",23:20,"8,8",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93920,2015-12-31,8096,CUENCA,CUENCA,948,"8,8","1,0","7,3",07:30,"10,3",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93921,2015-12-31,9814A,TORLA,HUESCA,1020,"6,0","2,4",23:50,"9,6",14:50,...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93922,2015-12-31,6325O,ALMERA AEROPUERTO,ALMERIA,21,"14,6","0,0","9,7",05:54,"19,6",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93923,2015-12-31,1542,PUERTO DE LEITARIEGOS,ASTURIAS,1530,"0,2","0,0","-1,2",06:00,"1,5",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93924,2015-12-31,C129Z,TAZACORTE,STA. CRUZ DE TENERIFE,62,"18,4","0,0","15,7",08:30,"21,2",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93925,2015-12-31,1111X,SANTANDER,CANTABRIA,52,"11,3","0,0","8,3",23:40,"14,3",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93926,2015-12-31,4642E,"HUELVA, RONDA ESTE",HUELVA,19,"15,2","4,8","11,7",00:06,"18,6",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93927,2015-12-31,2422,VALLADOLID,VALLADOLID,735,"5,6","0,0","2,2",23:30,"9,0",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93928,2015-12-31,C139E,LA PALMA AEROPUERTO,STA. CRUZ DE TENERIFE,33,"19,0","0,0","16,5",23:51,"21,6",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93929,2015-12-31,5051X,HUSCAR,GRANADA,1092,21,"1,1","5,8",14:30,"0,0",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93930,2015-12-31,5910,"ROTA, BASE NAVAL",CADIZ,21,"18,1","3,2","15,9",23:00,"20,3",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93931,2015-12-31,9091R,VITORIA GASTEIZ AEROPUERTO,ARABA/ALAVA,513,"5,6",Ip,"-0,9",23:24,"12,1",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93932,2015-12-31,4549Y,AYAMONTE,HUELVA,2,"15,4","1,3","13,0",21:30,"17,8",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93933,2015-12-31,3130C,SIGENZA,GUADALAJARA,1005,"6,6","4,6",20:00,"8,7",14:00,...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93934,2015-12-31,2737E,LAGUNAS DE SOMOZA,LEON,1020,"2,4","0,1","-1,1",05:20,"5,9",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93935,2015-12-31,1210X,CABO PEAS,ASTURIAS,100,"0,0",26,"2,5","9,7",00:10,...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93936,2015-12-31,B954,"IBIZA, AEROPUERTO",ILLES BALEARS,6,"15,0","0,0","10,3",02:05,"19,8",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93937,2015-12-31,C439J,GMAR,STA. CRUZ DE TENERIFE,115,"17,1","0,0","13,9",23:10,"20,3",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93938,2015-12-31,3469A,CCERES,CACERES,394,"9,8","0,0","6,8",23:50,"12,7",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93939,2015-12-31,8050X,JVEA/ XBIA,ALICANTE,15,"14,0","0,0","6,3",02:30,"21,7",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93940,2015-12-31,9262,PAMPLONA,NAVARRA,450,"10,0","0,0","6,1","14,0",Error,...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93941,2015-12-31,9263D,PAMPLONA AEROPUERTO,NAVARRA,459,"6,8","0,0","1,8",23:59,"11,9",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93942,2015-12-31,3044X,CAIZARES,CUENCA,928,"8,2","2,8","6,4",23:50,"10,1",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93943,2015-12-31,3195,"MADRID, RETIRO",MADRID,667,"10,7","0,1","9,2",20:30,"12,2",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93944,2015-12-31,B893,"MENORCA, AEROPUERTO",ILLES BALEARS,91,"13,8","0,0","9,7",01:45,"17,9",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93945,2015-12-31,9573X,ALCAIZ,TERUEL,334,"7,8","0,0","2,5",00:10,"13,2",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93946,2015-12-31,8416,VALNCIA,VALENCIA,11,"16,2","0,0","12,8","19,6","1,6",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93947,2015-12-31,7119B,CARAVACA DE LA CRUZ,MURCIA,643,"11,5","0,0","4,2",01:40,"18,8",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error
93948,2015-12-31,0255B,SANTA SUSANNA,BARCELONA,40,"10,3","0,0","5,2",05:30,"15,4",...,Error,Error,Error,Error,Error,Error,Error,Error,Error,Error

In [1]:
combined_csv.to_csv( "datosMeteo.csv", index=False, encoding='utf-8', sep=";")

NameError: name 'combined_csv' is not defined

In [17]:
datos2018csv.columns = headers

In [18]:
datos2018csv.head(3)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,htmin,tmax,htmax,dir,velmedia,racha,horaracha,sol,presmax,horapresmax,presmin,horapresmin
0,2018-01-01,4220X,PUEBLA DE DON RODRIGO,CIUDAD REAL,486,"6,2","0,0","0,2",08:00,"12,3",13:30,24,"1,4","8,9",15:20,NaN,NaN,NaN,NaN,NaN
1,2018-01-01,C447A,TENERIFE NORTE AEROPUERTO,STA. CRUZ DE TENERIFE,632,"15,8","0,0","12,3",07:08,"19,3",15:37,99,"1,7","8,3",Varias,"4,3","959,2",Varias,"956,3",15
2,2018-01-01,6106X,ANTEQUERA,MALAGA,408,"9,0","0,0","3,1",08:20,"14,9",14:10,04,"0,3","5,3",16:30,"986,5",10,"983,4",15,NaN

In [19]:
datos2018csv.to_csv('datos2018headers.csv')